FROM nginx:alpine

# Copy custom main nginx config
COPY nginx.main.conf /etc/nginx/nginx.conf
RUN chmod 644 /etc/nginx/nginx.conf && chown root:root /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
